# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TheBrockEllis
email: brock@sharproot.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site. It's pretty silly. That is all.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thebrockellis.com" # the base hostname & protocol for your site
twitter_username: TheBrockEllis
github_username:  TheBrockEllis

# Build settings
markdown: kramdown

paginate_path: 'blog/:num'
paginate: 5
timezone: America/Chicago
layout_dir: ./_layouts
destination: ./_sites

gems: [jekyll-paginate]

